# Generated by Codex on 2026-08-27

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_agent_staff_profile_management_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentprofile",
            name="discount_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[MinValueValidator(0), MaxValueValidator(100)],
            ),
        ),
    ]
