# Generated by Django 5.1.4 on 2026-09-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_productvariant_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='unit_type',
            field=models.CharField(blank=True, choices=[('piece', 'Piece'), ('sheet', 'Sheet'), ('panel', 'Panel'), ('board', 'Board'), ('box', 'Box'), ('set', 'Set'), ('running_foot', 'Running Foot'), ('square_foot', 'Square Foot')], max_length=30),
        ),
    ]
