# Generated by Django 5.1.4 on 2026-09-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_productvariant_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
