# Generated by Codex on 2026-08-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_address_district_timestamps"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="agent_code_snapshot",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="order",
            name="agent_discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="agent_discount_percentage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="order",
            name="subtotal_before_agent_discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
