# Generated by Django 5.1.4 on 2026-09-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_variant_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
