# Generated by Django 5.1.4 on 2026-09-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_agent_reward_points_order_promo_code_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='pricing_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('promo', 'Promo'), ('subpromo', 'Subpromo')], default='normal', max_length=12),
        ),
    ]
