# Generated by Django 5.1.4 on 2026-09-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderitem_pricing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='gstin',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
