# Generated by Django 5.1.4 on 2026-09-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_address_gstin'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_gstin',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
