# Generated by Django 5.1.4 on 2026-09-15 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_billing_gstin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceCounter',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('next_value', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_from_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='gst_rate_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=32, unique=True)),
                ('invoice_type', models.CharField(choices=[('B2C', 'B2C'), ('B2B', 'B2B')], max_length=3)),
                ('invoice_date', models.DateTimeField()),
                ('company_name', models.CharField(max_length=180)),
                ('company_address', models.TextField(blank=True)),
                ('company_email', models.EmailField(blank=True, max_length=254)),
                ('company_mobile', models.CharField(blank=True, max_length=30)),
                ('company_gstin', models.CharField(blank=True, max_length=15)),
                ('from_address', models.TextField()),
                ('billing_name', models.CharField(blank=True, max_length=140)),
                ('billing_address', models.TextField(blank=True)),
                ('billing_phone', models.CharField(blank=True, max_length=24)),
                ('billing_gstin', models.CharField(blank=True, max_length=15)),
                ('shipping_name', models.CharField(blank=True, max_length=140)),
                ('shipping_address', models.TextField(blank=True)),
                ('shipping_phone', models.CharField(blank=True, max_length=24)),
                ('shipping_state', models.CharField(blank=True, max_length=100)),
                ('shipping_state_code', models.CharField(blank=True, max_length=3)),
                ('shipping_gstin', models.CharField(blank=True, max_length=15)),
                ('taxable_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cgst_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sgst_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('igst_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('wallet_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('round_off', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_in_words', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_invoices', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='orders.order')),
            ],
            options={
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=180)),
                ('hsn_code', models.CharField(blank=True, max_length=20)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(max_length=12)),
                ('taxable_unit_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.invoice')),
            ],
        ),
    ]
